
-- ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
--        'PTRATIO', 'B', 'LSTAT', 'MEDV']

-- DROP TABLE IF EXISTS boston_housing_complete;
-- DROP TABLE IF EXISTS boston_housing_training;
-- DROP TABLE IF EXISTS boston_housing_testing;

CREATE TABLE IF NOT EXISTS boston_housing_complete (
    CRIM NUMERIC NOT NULL,
    ZN NUMERIC NOT NULL,
    INDUS NUMERIC NOT NULL,
    CHAS NUMERIC NOT NULL,
    NOX NUMERIC NOT NULL,
    RM NUMERIC NOT NULL,
    AGE NUMERIC NOT NULL,
    DIS NUMERIC NOT NULL,
    RAD NUMERIC NOT NULL,
    TAX NUMERIC NOT NULL,
    PTRATIO NUMERIC NOT NULL,
    B NUMERIC NOT NULL,
    LSTAT NUMERIC NOT NULL,
    MEDV NUMERIC NOT NULL,
    ID INT NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS boston_housing_training (
    CRIM NUMERIC NOT NULL,
    ZN NUMERIC NOT NULL,
    INDUS NUMERIC NOT NULL,
    CHAS NUMERIC NOT NULL,
    NOX NUMERIC NOT NULL,
    RM NUMERIC NOT NULL,
    AGE NUMERIC NOT NULL,
    DIS NUMERIC NOT NULL,
    RAD NUMERIC NOT NULL,
    TAX NUMERIC NOT NULL,
    PTRATIO NUMERIC NOT NULL,
    B NUMERIC NOT NULL,
    LSTAT NUMERIC NOT NULL,
    MEDV NUMERIC NOT NULL,
    ID INT NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS boston_housing_testing (
    CRIM NUMERIC NOT NULL,
    ZN NUMERIC NOT NULL,
    INDUS NUMERIC NOT NULL,
    CHAS NUMERIC NOT NULL,
    NOX NUMERIC NOT NULL,
    RM NUMERIC NOT NULL,
    AGE NUMERIC NOT NULL,
    DIS NUMERIC NOT NULL,
    RAD NUMERIC NOT NULL,
    TAX NUMERIC NOT NULL,
    PTRATIO NUMERIC NOT NULL,
    B NUMERIC NOT NULL,
    LSTAT NUMERIC NOT NULL,
    MEDV NUMERIC NOT NULL,
    ID INT NOT NULL,
    PRIMARY KEY (ID)
);

-- SELECT * FROM boston_housing_complete

-- SELECT * FROM boston_housing_testing

-- SELECT * FROM boston_housing_training